# Generated by Django 5.1 on 2024-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
